services:
  drupal:
    build:
      context: ../
      dockerfile: .build/drupal/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - DRUPAL_DOMAIN=${DRUPAL_DOMAIN}
    image: localgov-storybook-drupal:latest
    user: "${USER_ID}"
    env_file: .env
    networks:
      - webnet

  storybook:
    build:
      context: ../
      dockerfile: .build/storybook/Dockerfile
      args:
        - USER_ID=${USER_ID}
    image: localgov-storybook:latest
    user: "${USER_ID}"
    env_file: .env
    depends_on:
      - drupal
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
